### PR TITLE
Added allow_if_user to replace allow_if.

### PR DESCRIPTION
**Pull request by jacobian**
This allows passing the entire user resource, which means you can switch on
interesting things like `user['two_factor_enabled']`.

My Ruby-fu is semi-weak, so please LMK if this is the right way to be doing this.

### CODE REVIEW

**Comment by wuputah** [comment]
I'd like to maintain backwards compatibility (and tests) for `allow_if`. If you're not comfortable drafting that up, I could take a shot.

Please also update the README. :grin:

**Comment by jacobian** [comment]
@wuputah I believe I did maintain compatibility with `allow_if` -- I didn't remove any tests, at least. Do you mean the deprecation warning? So just keep both `allow_if` and `allow_if_user` to peacefully co-exist?

D'oh on the README, I should know better. On it.

**Comment by jacobian** [comment]
@wuputah this more like what you had in mind?

**Comment by wuputah** [comment]
Yes! Though it doesn't seem like you're deprecating `allow_if` now, though that's a design decision (to have both options or only one).

**Comment by dpiddy** [comment]
:clap:

**Pull request merged**
