### PR TITLE
Update call to OpenSSL Cipher for ruby 2.4

### LINKED ISSUE #54: OpenSSL::Cipher::Cipher is deprecated in Ruby 2.4.0
Since upgrading to Ruby 2.4.0, I've been getting this warning:

```
[...]/ruby/gems/2.4.0/gems/heroku-bouncer-0.7.1/lib/heroku/bouncer/lockbox.rb:24: warning: constant OpenSSL::Cipher::Cipher is deprecated
```

### PR DESCRIPTION
**Pull request by maxbeizer**
`OpenSSL::Cipher::Cipher` is [deprecated](https://ruby.github.io/openssl/OpenSSL/Cipher/Cipher.html) in Ruby 2.4.x

This PR changes cipher initialization to the right class if using Ruby 2.4.x.

Closes #54

### CODE REVIEW

**Comment by maxbeizer** [comment]
From CI for the 2.0 version:

```
Gem::InstallError: rack requires Ruby version >= 2.2.2.

...

An error occurred while installing rack (2.0.3), and Bundler cannot continue.
```

Looks like it's trying to install Rack and Rack requires Ruby 2.2.2. Perhaps it's worth putting a conditional in the gemspec to support older version of Ruby or dropping support for Ruby 2.1 and below

**Comment by mathias** [comment]
We need this as well. Any chance someone can take a look at this?

**Comment by wuputah** [comment]
Yes, you can!

I won't merge PRs that don't have passing tests. I appreciate that something may have changed previously to cause this and so you're inheriting a problem you didn't anticipate fixing, but that's the way of the world sometimes.

**Comment by mathias** [comment]
Per the above, I think this is more of a question of who makes the decision about whether we include a conditional in the gemspec. I can do that, if we're agreed that's the solution.

**Comment by maxbeizer** [comment]
@wuputah Do you have an opinion on dropping support of Ruby <= 2.1? Official support of Ruby 2.1 [has ended](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/)

**Comment by wuputah** [comment]
Dropping support for unsupported versions of Ruby is fine. I usually bump the minor version for this, in case we need to come back and patch this version for some reason.

**Comment by wuputah** [comment]
I can take care of that at release-time, though.

**Comment by maxbeizer** [comment]
thanks @wuputah 😄 . Now if only I can get travis to stop building old versions of ruby ...

**Comment by maxbeizer** [comment]
@wuputah this is now green and ready for your review.

**Comment by wuputah** [comment]
Thanks Max. This looks good. I considered moving the logic into load time / class scope, but I'm worried about thread safety, so I think I will leave it as-is.

Just FYI, you may not want to upgrade to 2.4 just yet:
https://bugs.ruby-lang.org/issues/13772

**Comment by maxbeizer** [comment]
thanks again @wuputah

**Pull request merged**
